site_name: Meine Docs
site_url: https://southx1337.github.io/docs/
site_author: sOUTHX
site_description: You tell me
copyright: Copyright &copy; 2021 - 2021 sOUTHX


theme:
  name: material


nav:
  - Home: index.md
  - Webhost:
    - DNS Einstellungen: webhost/dns.md
    - Folgt: webhost/dns.md
  - Services:
    - ReachMe: services/reach.md
    - Terminfinder: services/terminfinder.md
    - Private Bin: services/privatebin.md