site_name: Meine Docs
site_url: https://southx1337.github.io/
site_author: sOUTHX
site_description: You tell me
copyright: Copyright &copy; 2021 - 2021 sOUTHX


theme:
  name: material


nav:
  - Home: index.md
  - Services:
    - Private Bin: services/privatebin.md