site_name: Webhost Dokumentation
site_url: https://southx1337.github.io/docs/
site_author: Jonas
site_description: You tell me
copyright: Copyright &copy; 2021 - 2021 sOUTHX


theme:
  name: material
  palette:
    primary: pink
    accent: teal
    scheme: slate


nav:
  - Home: index.md
  - Webhost:
    - DNS Einstellungen: webhost/dns.md
    - Weitere Einstellungen: https://hostinghandbuch.de/